# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='omnisearch',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\trpc.proto\x12\nomnisearch\"-\n\x0e\x45xecuteRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\x12\r\n\x05\x64\x61tas\x18\x02 \x03(\t\"\x19\n\x06Vector\x12\x0f\n\x07\x65lement\x18\x01 \x03(\x02\"%\n\x08MetaData\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"i\n\x0c\x45xecuteReply\x12\x0c\n\x04nums\x18\x01 \x01(\x03\x12#\n\x07vectors\x18\x02 \x03(\x0b\x32\x12.omnisearch.Vector\x12&\n\x08metadata\x18\x03 \x03(\x0b\x32\x14.omnisearch.MetaData\"\x10\n\x0eHealthyRequest\"\x1f\n\x0cHealthyReply\x12\x0f\n\x07healthy\x18\x01 \x01(\t\"\x11\n\x0fIdentityRequest\"\x83\x01\n\rIdentityReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05input\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\x12\x11\n\tdimension\x18\x06 \x01(\t\x12\x12\n\nmetricType\x18\x07 \x01(\t2\xd6\x01\n\x08Operator\x12\x41\n\x07\x45xecute\x12\x1a.omnisearch.ExecuteRequest\x1a\x18.omnisearch.ExecuteReply\"\x00\x12\x41\n\x07Healthy\x12\x1a.omnisearch.HealthyRequest\x1a\x18.omnisearch.HealthyReply\"\x00\x12\x44\n\x08Identity\x12\x1b.omnisearch.IdentityRequest\x1a\x19.omnisearch.IdentityReply\"\x00\x62\x06proto3'
)




_EXECUTEREQUEST = _descriptor.Descriptor(
  name='ExecuteRequest',
  full_name='omnisearch.ExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='omnisearch.ExecuteRequest.urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datas', full_name='omnisearch.ExecuteRequest.datas', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=70,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='omnisearch.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='omnisearch.Vector.element', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=97,
)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='omnisearch.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='omnisearch.MetaData.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='omnisearch.MetaData.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=136,
)


_EXECUTEREPLY = _descriptor.Descriptor(
  name='ExecuteReply',
  full_name='omnisearch.ExecuteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nums', full_name='omnisearch.ExecuteReply.nums', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='omnisearch.ExecuteReply.vectors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='omnisearch.ExecuteReply.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=243,
)


_HEALTHYREQUEST = _descriptor.Descriptor(
  name='HealthyRequest',
  full_name='omnisearch.HealthyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=261,
)


_HEALTHYREPLY = _descriptor.Descriptor(
  name='HealthyReply',
  full_name='omnisearch.HealthyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthy', full_name='omnisearch.HealthyReply.healthy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=294,
)


_IDENTITYREQUEST = _descriptor.Descriptor(
  name='IdentityRequest',
  full_name='omnisearch.IdentityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=313,
)


_IDENTITYREPLY = _descriptor.Descriptor(
  name='IdentityReply',
  full_name='omnisearch.IdentityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='omnisearch.IdentityReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='omnisearch.IdentityReply.endpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='omnisearch.IdentityReply.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='omnisearch.IdentityReply.input', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='omnisearch.IdentityReply.output', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='omnisearch.IdentityReply.dimension', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metricType', full_name='omnisearch.IdentityReply.metricType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=447,
)

_EXECUTEREPLY.fields_by_name['vectors'].message_type = _VECTOR
_EXECUTEREPLY.fields_by_name['metadata'].message_type = _METADATA
DESCRIPTOR.message_types_by_name['ExecuteRequest'] = _EXECUTEREQUEST
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['ExecuteReply'] = _EXECUTEREPLY
DESCRIPTOR.message_types_by_name['HealthyRequest'] = _HEALTHYREQUEST
DESCRIPTOR.message_types_by_name['HealthyReply'] = _HEALTHYREPLY
DESCRIPTOR.message_types_by_name['IdentityRequest'] = _IDENTITYREQUEST
DESCRIPTOR.message_types_by_name['IdentityReply'] = _IDENTITYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecuteRequest = _reflection.GeneratedProtocolMessageType('ExecuteRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.ExecuteRequest)
  })
_sym_db.RegisterMessage(ExecuteRequest)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.Vector)
  })
_sym_db.RegisterMessage(Vector)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.MetaData)
  })
_sym_db.RegisterMessage(MetaData)

ExecuteReply = _reflection.GeneratedProtocolMessageType('ExecuteReply', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.ExecuteReply)
  })
_sym_db.RegisterMessage(ExecuteReply)

HealthyRequest = _reflection.GeneratedProtocolMessageType('HealthyRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHYREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.HealthyRequest)
  })
_sym_db.RegisterMessage(HealthyRequest)

HealthyReply = _reflection.GeneratedProtocolMessageType('HealthyReply', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHYREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.HealthyReply)
  })
_sym_db.RegisterMessage(HealthyReply)

IdentityRequest = _reflection.GeneratedProtocolMessageType('IdentityRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.IdentityRequest)
  })
_sym_db.RegisterMessage(IdentityRequest)

IdentityReply = _reflection.GeneratedProtocolMessageType('IdentityReply', (_message.Message,), {
  'DESCRIPTOR' : _IDENTITYREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:omnisearch.IdentityReply)
  })
_sym_db.RegisterMessage(IdentityReply)



_OPERATOR = _descriptor.ServiceDescriptor(
  name='Operator',
  full_name='omnisearch.Operator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=450,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='omnisearch.Operator.Execute',
    index=0,
    containing_service=None,
    input_type=_EXECUTEREQUEST,
    output_type=_EXECUTEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Healthy',
    full_name='omnisearch.Operator.Healthy',
    index=1,
    containing_service=None,
    input_type=_HEALTHYREQUEST,
    output_type=_HEALTHYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Identity',
    full_name='omnisearch.Operator.Identity',
    index=2,
    containing_service=None,
    input_type=_IDENTITYREQUEST,
    output_type=_IDENTITYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERATOR)

DESCRIPTOR.services_by_name['Operator'] = _OPERATOR

# @@protoc_insertion_point(module_scope)
