# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_pb2 as rpc__pb2


class OperatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/omnisearch.Operator/Execute',
        request_serializer=rpc__pb2.ExecuteRequest.SerializeToString,
        response_deserializer=rpc__pb2.ExecuteReply.FromString,
        )
    self.Healthy = channel.unary_unary(
        '/omnisearch.Operator/Healthy',
        request_serializer=rpc__pb2.HealthyRequest.SerializeToString,
        response_deserializer=rpc__pb2.HealthyReply.FromString,
        )
    self.Identity = channel.unary_unary(
        '/omnisearch.Operator/Identity',
        request_serializer=rpc__pb2.IdentityRequest.SerializeToString,
        response_deserializer=rpc__pb2.IdentityReply.FromString,
        )


class OperatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Healthy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Identity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=rpc__pb2.ExecuteRequest.FromString,
          response_serializer=rpc__pb2.ExecuteReply.SerializeToString,
      ),
      'Healthy': grpc.unary_unary_rpc_method_handler(
          servicer.Healthy,
          request_deserializer=rpc__pb2.HealthyRequest.FromString,
          response_serializer=rpc__pb2.HealthyReply.SerializeToString,
      ),
      'Identity': grpc.unary_unary_rpc_method_handler(
          servicer.Identity,
          request_deserializer=rpc__pb2.IdentityRequest.FromString,
          response_serializer=rpc__pb2.IdentityReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'omnisearch.Operator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
