# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssd_label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssd_label.proto',
  package='label',
  syntax='proto3',
  serialized_pb=_b('\n\x0fssd_label.proto\x12\x05label\";\n\tLabelItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\"-\n\x0bMSCOCOLabel\x12\x1e\n\x04item\x18\x01 \x03(\x0b\x32\x10.label.LabelItemb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LABELITEM = _descriptor.Descriptor(
  name='LabelItem',
  full_name='label.LabelItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='label.LabelItem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='label.LabelItem.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='label.LabelItem.display_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=85,
)


_MSCOCOLABEL = _descriptor.Descriptor(
  name='MSCOCOLabel',
  full_name='label.MSCOCOLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='label.MSCOCOLabel.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=132,
)

_MSCOCOLABEL.fields_by_name['item'].message_type = _LABELITEM
DESCRIPTOR.message_types_by_name['LabelItem'] = _LABELITEM
DESCRIPTOR.message_types_by_name['MSCOCOLabel'] = _MSCOCOLABEL

LabelItem = _reflection.GeneratedProtocolMessageType('LabelItem', (_message.Message,), dict(
  DESCRIPTOR = _LABELITEM,
  __module__ = 'ssd_label_pb2'
  # @@protoc_insertion_point(class_scope:label.LabelItem)
  ))
_sym_db.RegisterMessage(LabelItem)

MSCOCOLabel = _reflection.GeneratedProtocolMessageType('MSCOCOLabel', (_message.Message,), dict(
  DESCRIPTOR = _MSCOCOLABEL,
  __module__ = 'ssd_label_pb2'
  # @@protoc_insertion_point(class_scope:label.MSCOCOLabel)
  ))
_sym_db.RegisterMessage(MSCOCOLabel)


# @@protoc_insertion_point(module_scope)
