# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'operators/**'
    branches:
      - master
      - 0.1.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: install requirements
      run: |
        sudo apt install python3-pip python3-setuptools
        pip3 install wheel pylint
    - name: make api
      run: make api
    - name: push to dockerhub
      env:
        DOCKERHUB_TOKEN: ${{ secrets.dockerhub }}
      run: make push
